server {
    listen 80;
    server_tokens off;

    # Перенаправляем запросы к API на бэкенд
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/api/;
    }

    # Перенаправляем запросы к админке на бэкенд
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/admin/;
    }

    # Раздаём медиафайлы (картинки котиков, которые загрузят пользователи)
    location /media/ {
        alias /media/;
    }

    # Раздаём статику (фронтенд и стили админки)
    location / {
        alias /staticfiles/;
        index  index.html index.htm;
        try_files $uri /index.html;
    }
}
